name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Download APK Builder
        uses: actions/checkout@v4
        with:
          repository: 'juunini/html-to-apk'
          path: 'builder'

      - name: Build
        run: |
          mkdir build
          cp index.html build/
          npx cordova create app com.example.app MyAIApp
          cp index.html app/www/index.html
          cd app
          npx cordova platform add android
          npx cordova build android

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Mobile-App
          path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
